// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Custom domain for GitHub Pages.
export default defineConfig({
	site: 'https://supercharger.richpolanco.com',
	integrations: [
		starlight({
			title: 'Supercharger',
			description:
				'Local-first technical support training, job prep, and Docker sandbox lessons generated by your AI coding assistant.',
			head: [
				{
					tag: 'meta',
					attrs: {
						name: 'keywords',
						content:
							'technical support training, support engineer interview prep, AI coding assistant, Docker sandbox lessons, job prep, support enablement, technical readiness',
					},
				},
				{
					tag: 'meta',
					attrs: {
						property: 'og:image',
						content: 'https://supercharger.richpolanco.com/screenshots/home.png',
					},
				},
				{
					tag: 'meta',
					attrs: {
						property: 'og:image:alt',
						content: 'Supercharger app showing sample learning tracks and job prep materials.',
					},
				},
				{
					tag: 'meta',
					attrs: {
						name: 'twitter:card',
						content: 'summary_large_image',
					},
				},
				{
					tag: 'meta',
					attrs: {
						name: 'twitter:image',
						content: 'https://supercharger.richpolanco.com/screenshots/home.png',
					},
				},
			],
			social: [
				{
					icon: 'github',
					label: 'GitHub',
					href: 'https://github.com/mrpolanco/Supercharger',
				},
			],
			sidebar: [
				{
					label: 'Introduction',
					items: [
						{ label: 'What is Supercharger?', slug: 'introduction/what-is-supercharger' },
						{ label: 'Quickstart', slug: 'introduction/quickstart' },
					],
				},
				{
					label: 'Case studies',
					items: [
						{
							label: 'Product Support Specialist',
							slug: 'case-studies/product-support-specialist',
						},
					],
				},
				{
					label: 'Guides',
					items: [
						{ label: 'Generating a track', slug: 'guides/generating-a-track' },
						{ label: 'Slash commands', slug: 'guides/slash-commands' },
						{ label: 'Prepare me for this job', slug: 'guides/job-prep' },
						{ label: 'Product docs onboarding', slug: 'guides/product-docs-onboarding' },
						{ label: 'Working through a lesson', slug: 'guides/lessons' },
						{ label: 'Troubleshooting', slug: 'guides/troubleshooting' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'Content spec', slug: 'reference/content-spec' },
						{ label: 'Architecture', slug: 'reference/architecture' },
						{ label: 'FAQ', slug: 'reference/faq' },
					],
				},
			],
		}),
	],
});
